User roles 22 part2
NicolasDuciaume/SYSC4806_Web_App pull request #61
Opened 2022-03-23 18:33 UTC by Calacorm

WIP

Trying to create a ability to change a role and persit it

2022-04-03 22:13 UTC, Calacorm commented
Added an update to add dynamic table support. Plan to use this tech to make a table we can edit user roles on for part of the admin UI interface

2022-04-04 15:43 UTC, Calacorm commented
The table no shows relevant data.
The users are generated from a json file so that needs to be hooked into the JPA repository functions later on.
The table shows the users and has an edit button. THe button is not hooked up yet
Seems to be working, just need to hook up the button and hook into JPArepository instead of the json file and then liink the page to a demo button or something once you log in. And Ill have a minimum viable feature addition

2022-04-05 00:59 UTC, Calacorm commented
Going to do polish and add tests and make sure CI passes now

2022-04-05 01:01 UTC, Calacorm commented on src/main/resources/templates/Registration.html
>  <head>
Massive tool for doing dynamic tables, very cool!
https://datatables.net/

2022-04-05 01:02 UTC, Calacorm commented on src/main/java/SYSC6/Project/user/User.java
> +@Setter
Lombok does all the boring getter setter bs for us! clean class

2022-04-05 01:04 UTC, Calacorm commented on src/main/java/SYSC6/Project/RoleType.java
> +    ADMIN (3, "admin");
The index parameter here is used to indicate the ordinal of the enum this role may upgrade to.
Its a bit silly, and we have an endpoint where we can just specify as well, but I implemented this system regardless

2022-04-05 01:04 UTC, Calacorm commented on src/main/java/SYSC6/Project/WebConfig.java
> +                .addResourceLocations("classpath:/css/", "classpath:/Javascript/", "classpath:/Images/", "classpath:/Datatable/", "classpath:/jquery/");
need an import in the html files? make sure to update this file!

2022-04-05 01:07 UTC, Calacorm commented on pom.xml
>  	</build>
Going to review this, some things I added I do not need since I added the files in manually to our resources folder

2022-04-05 01:22 UTC, NicolasDuciaume submitted a review, later dismissed
Looks good and functions as intended yet need to switch links to heroku for functioning on their system.

2022-04-05 01:40 UTC, cadsilva approved these changes

2022-04-05 01:51 UTC, nazifatanzim requested changes
Code looks good, but please add integration tests.

2022-04-05 02:43 UTC, Calacorm commented
Heroku links set

2022-04-05 02:45 UTC, Calacorm commented
Going to leave it in localhost mode for now until we need to show on heroku

2022-04-05 16:16 UTC, NicolasDuciaume approved these changes
Looks good, works as intended

2022-04-05 17:16 UTC, merged